//product
export const CATEGORIES_FETCHED = 'CATEGORIES_FETCHED'
export const SET_CATEGORY = 'SET_CATEGORY'
export const PRODUCTS_FETCHING = 'PRODUCTS_FETCHING'
export const PRODUCTS_FETCHED = 'PRODUCTS_FETCHED'
export const PRODUCTS_FETCHING_ERROR = 'PRODUCTS_FETCHING_ERROR'

//profile
export const ADD_TO_FAVORITES = 'ADD_TO_FAVORITES'
export const ADD_TO_CART = 'ADD_TO_CART'
export const DELETE_FROM_FAVORITES = 'DELETE_FROM_FAVORITES'